add caption for kayakkat
githubschool/engagement pull request #11
Opened 2019-02-12 20:40 UTC by kayakkat

CHANGE2 changed kayakkat to include Whoa! in caption

## Tasks remaining
-[ ] first task

2019-02-12 21:05 UTC, js3263827 commented on _posts/0000-01-05-kayakkat.md
> +Whoa!
👍

2019-02-12 21:07 UTC, js3263827 requested changes
@kayakkat merge when you want.

2019-02-12 21:08 UTC, githubteacher requested changes
@kayakkat this looks great! 

I left a suggested action for you, but you can feel free to merge without fixing it if you want!

2019-02-12 21:08 UTC, githubteacher commented on _posts/0000-01-05-kayakkat.md
> +Whoa!
Far out! 👋 🌊 😮

2019-02-12 21:08 UTC, githubteacher commented on _posts/0000-01-05-kayakkat.md
>  Caption here
Hey! I think we can remove the "Caption here" line. What do you think? 😄 ✨

2019-02-12 21:27 UTC, js3263827 approved these changes

2019-02-13 16:14 UTC, githubteacher approved these changes

2019-02-13 16:15 UTC, merged